### PR TITLE
Update CLI help text

### PR DESCRIPTION
**Pull request by JChanceHud**
The help text for the cli is missing some features. I added some options and took a guess at others. Also, there are conflicting aliases between `port`, `produce` and `proxy`.

### CODE REVIEW

**Comment by SilentCicero** [comment]
@JChanceHud Thank you for this, apologies for getting back late, we will get this in for the v1.1 release!

**Comment by SilentCicero** [comment]
@JChanceHud any chance you can rebase this with the new master? If not, can do this by hand but likely later on.

**Comment by JChanceHud** [comment]
I ran a simple rebase against the master branch but it seems to have made a mess :/

I also see there are lots more CLI options added with no documentation in the recent commits. I think it makes sense to close this PR and just start a different branch with the help text updated.

**Comment by SilentCicero** [comment]
Oh yes! You are right, some of these are more experimental and require a
bigger story to profile though.

We can do most of them though.

**Pull request closed without merging**
